# -*- coding: utf-8 -*-
"""indexmatrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4m0r_RSl6wSHSYEtFwKcpHpWh6D7M4s

<center><img src="https://i.imgur.com/zRrFdsf.png" width="700"></center>






# Neighboorhood and Spatial Correlation.

## Getting ready

### Libraries needed

Let's verify:
"""

!pip show pysal pandas geopandas

## needed in Colab
# !pip install pysal

"""### Data to use

Let me get two maps:

1. The USA map, at states level,  directly from census.gov, which has a good quality.
"""

import geopandas as gpd

url = "https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_state_500k.zip"
us_states = gpd.read_file(url)
us_states.info(),us_states.crs.to_epsg(),us_states.crs.is_projected

"""Notice this map has basic information per state. Also, notice the current crs will plot this:"""

us_states.plot()

"""Let's reproject this map:"""

us_states=us_states.to_crs(5070)
us_states.plot()

"""Let's use the state name as index, that would help an easier identification of the places when we see most outputs (otherwise we will see just numerical indexes) :"""

us_states.set_index('NAME', inplace=True)
us_states.head()

"""Let's subset the us_states for most examples (mainly Part I, II and III):"""

someStates=['Utah','Colorado','Arizona','New Mexico', 'Florida','Georgia','Alabama']
sub_us=us_states[us_states.index.isin(someStates)]
sub_us

"""2. A map of Peru, at the 'distrito' level (similar to municipality in the USA - not exactly the same). The map comes from an unoffical [website](https://www.geogpsperu.com/p/descargas.html). Some columns have been added."""

peruDataLink="https://github.com/CienciaDeDatosEspacial/dataSets/raw/refs/heads/main/PERU/PeruMaps.gpkg"
peru_distritos=gpd.read_file(peruDataLink,layer='distritos')

# some basic info
peru_distritos.info(),peru_distritos.crs.to_epsg(),peru_distritos.crs.is_projected

"""Let's reproject and plot:"""

peru_distritos=peru_distritos.to_crs(32718)
peru_distritos.plot()

"""Besides the spatial units (DEPARTAMEN, PROVINCIA, DISTRITO, and Ubigeo - "Ubigeo" is a code ), you have:
 - **Poblacion**: Population (2017)
 - **Superficie**: Area               
 - **IDH2019**: Human Development Index for DISTRITO (2019)                   
 - **Educ_sec_comp2019_pct**: Share of Population that finished High-School (2019)     
 - **NBI2017_pct**: Share of Population with poverty at the household level aggregated by DISTRITO. This index ("Unsatisfied Basic Needs") uses observable living conditions rather than income alone (2017).
 - **Viv_sin_serv_hig2017_pct**: Share of housing units that have no sanitation infrastructure aggregated by  DISTRITO (2017)

The last two sections (IV and V) will need these **social data**.


Notice we should not use the 'distrito' name as index, because several of them are repeated:
"""

peru_distritos[peru_distritos['DISTRITO'].duplicated()]

"""Let's use 'Ubigeo', although it is not the best solution"""

# of course
peru_distritos[peru_distritos['Ubigeo'].duplicated()]

#then
peru_distritos.set_index('Ubigeo', inplace=True)

"""**NOTICE** both projections used above are equal-area ones, which are standard for distance computations in meters.

## I. Who is my neighbor?

In spatial analysis, the intuitive concept of a “neighbor” can be operationalized in multiple ways.

So far, we have identified neighbors using geometric operations such as buffering, spatial joins, and overlays. Now, let’s consider the distance matrix:
"""

sub_us.geometry.apply\
(lambda state: sub_us.distance(state)/1000)

"""You can see roughly the distances here:"""

sub_us.explore(zoom_start=6)

"""From this matrix and plot, you’ll notice that neighboring features have a distance of zero—this occurs when two polygons share a boundary (i.e., they are contiguous). This observation helps illustrate the different approaches to defining neighbors:

1. Binary Relationships:

* Contiguity: Two polygons are considered neighbors if they share any portion of their boundary—whether at a point, along a line segment, or more extensively. In the distance matrix, such pairs show a distance of zero, reflecting direct spatial adjacency.
* Ranked Proximity: In this approach, assume there each node has ranked all the other potential neighbors by their mutual distance. Then, you request K neighbors, and you get the K closest ones to you from that ranking.

* Binary Proximity: In this approach, you accept as neighbors the one that are within a threshold distance. It is binary because either they are or not negihbors.  This approach will not need neighborr are contiguous (touching each other on the boundaries)


2. Continuous Relationships

* Continous-Proximity: Two features are considered neighbors if the distance between them falls below a specified threshold. It is continous because every accepted neighbor has some numerical level or weight of proximity. This approach will not need neighborr are contiguous (touching each other on the boundaries)
* Shared Border Length: The relationship is graded by  the length of the shared boundary between contiguous neighbors. Longer shared borders imply stronger "neighborhoodness".

Using matrices for this relationships—rather than raw geometries—is essential for the mathematical abstraction/representation and numerical computation required in upcoming spatial analytics techniques.

We will introduce some of PySAL (libpysal), which is designed to handle spatial relationship matrices and integrates seamlessly with GeoPandas. PySAL uses graph-based representations of these matrice, which  is not only more memory-efficient but also speeds up computation and simplifies visualization—especially for large or sparse spatial datasets.  A key concept in these graphs is the distinction between:

- Focal unit: the spatial feature (e.g., a state, county, or census tract) for which we are identifying neighbors.
- Neighbor(s): the other spatial units that are considered related to the focal unit based on a chosen criterion (e.g., contiguity, distance, or shared border length).

Let’s become familiar with the ```graph``` module in PySAL/libpysal, which provides a modern and flexible framework for constructing and working with spatial neighbor graphs.

"""

from libpysal.graph import Graph

# also for reproducibility!
from numpy.random import seed
seed(42)

"""### I.1 Binary matrices

#### I.1.1 Contiguity and Binary matrices

Take a look at the **queen** and **rook** relationship:

<center><img src="https://github.com/CienciaDeDatosEspacial/spatial_autoCorr/raw/main/rookQueen.png" width="700"></center>

From the image above:
- Your **rook** neighbor is whichever  shares a border with you (a borderline of at least two points). It is also known as the _Von Neumann_ neighbor.

- Your **queen** neighbor is whichever  shares a border or a corner with you (at least one point).It is also known as the _Moore_ neighbor.

Let's see how to get each set of neighbors

##### A. Rook

* The key idea: A focal polygon considers another polygon a neighbor if they share a common edge—that is, two or more connected points forming a line segment of positive length.
* The input: A GeoDataFrame (GDF) containing polygon geometries (e.g., states, counties, census tracts). Each row represents a spatial unit that can serve as a focal observation.
* The process: For each polygon (focal unit), the algorithm checks all other polygons to determine whether their boundaries intersect along a line segment (not just at a point).
* The output: A graph built from a binary adjacency matrix where each node represents a polygon (focal unit). An edge exists between two nodes only if they share a boundary segment. The corresponding adjacency matrix is binary.

Given our input for the examples is **sub_us**, let's run...
"""

rook=Graph.build_contiguity(sub_us,rook=True) # rook by default

"""Now let's check the ouput:

**a. adjacency**
"""

rook.adjacency

"""The previous results shows only the neighbors of the focals, to recreate a wide format:"""

import pandas as pd
pd.DataFrame(rook.adjacency).unstack()

"""We generally fill those missing values (not a neighbor) with zero."""

rook_Matrix=pd.DataFrame(rook.adjacency).unstack().fillna(0)
rook_Matrix

"""SInce we are going to use several times, we may create a custom procedure:"""

#instead of
# pd.DataFrame(rook.adjacency).unstack().fillna(0)
toWideMatrix=lambda g:pd.DataFrame(g.adjacency).unstack().fillna(0)

"""Notice we created this wide matrix for pedagogical purposes. It is not needed, specially if columns and rows are nor displayed.

**b. adjacency graph**

As we have a `GRAPH`, we can identify these neighborhood relationships via edges:
"""

##this will be used several times:
basic_arguments=dict(gdf=sub_us,node_kws=dict(color='red'), edge_kws=dict(alpha=0.4,color='blue'),zoom_start = 6)
rook.explore(**basic_arguments)

"""##### B. Queen

* The key idea: A focal polygon considers another polygon a neighbor if they share a common edge or a vertex (at least one point).
* The input: A GeoDataFrame (GDF) containing polygon geometries (e.g., states, counties, census tracts). Each row represents a spatial unit that can serve as a focal observation.
* The process: For each polygon (focal unit), the algorithm checks all other polygons to determine whether their boundaries intersect at any point or along a line segment.
* The output: A graph built from a binary adjacency matrix where each node represents a polygon (focal unit). An edge exists between two nodes only if they share a point or boundary segment. The corresponding adjacency matrix is binary.

Let's see what we get:

**a. adjacency matrix**
"""

queen=Graph.build_contiguity(sub_us,rook=False)

# applying our procedure:

queen_Matrix=toWideMatrix(queen)
queen_Matrix

"""**b. adjacency plot**"""

queen.explore(**basic_arguments)

"""
#### I.1.2 Ranked  proximity and Binary matrices: KNN

* The key idea: A focal polygon considers another polygon a neighbor if that second polygon is among the K closest polygons to the focal polygon, where “closeness” is measured by the distance between their geometric centroids (or any other user-supplied distance metric).  
* The input: A GeoDataFrame (GDF) containing polygon geometries. Each row represents a spatial unit that can serve as a focal observation.  
* The process: For each polygon (focal unit), the algorithm (1) computes the distance between its centroid and every other centroid, (2) ranks these distances, and (3) flags the K smallest distances as neighbors. Ties can be broken by random selection, ID order, or by including all tied candidates.  
* The output: A graph built from a binary adjacency matrix where each node represents a polygon (focal unit). An edge exists between two nodes whenever one polygon is among the K nearest neighbors of the other. The corresponding adjacency matrix is binary and, by construction, typically asymmetric unless a symmetric constraint is explicitly enforced.

If assume K is 3:

**a. adjacency matrix**"""

knn3 = Graph.build_knn(sub_us.representative_point(), # GDF
                                 k=3) # desired k

knn3_Matrix=toWideMatrix(knn3)
knn3_Matrix

"""**b. adjacency plot**"""

knn3.explore(**basic_arguments)

"""#### I.1.3 Band-based  proximity and Binary matrices:


* The key idea: A focal polygon considers another polygon a neighbor if the distance between them (usually centroid-to-centroid , or a pair of representative point) lies within a user-defined band.
* The input: A GeoDataFrame (GDF) containing polygon geometries for which a representative point is supplied. Each row represents a spatial unit that can serve as a focal observation, plus (optionally) an attribute column to use as a weight or ID.  
* The process: For each polygon (focal unit) the algorithm computes the distance to every other polygon and flags those whose distance falls inside the specified band.
* The output: A binary spatial graph (or adjacency structure) where each node represents a polygon. An edge exists between two nodes only if their mutual distance sits inside the chosen band. The corresponding adjacency matrix is binary and symmetric by construction.

Let's assume a 750 km distance band:
"""

band750k_Bi=Graph.build_distance_band(sub_us.representative_point(), threshold=750000)

band750k_Bi_Matrix=toWideMatrix(band750k_Bi)
band750k_Bi_Matrix

band750k_Bi.explore(**basic_arguments)

"""### I.2 Continuous Matrices

#### I.2.1 Continuos Distance band-based Proximity

* The key idea: A focal polygon considers another polygon a neighbor if the distance between them (usually centroid-to-centroid , or a pair of representative point) lies within a user-defined band.
* The input: A GeoDataFrame (GDF) containing polygon geometries for which a representative point is supplied. Each row represents a spatial unit that can serve as a focal observation, plus (optionally) an attribute column to use as a weight or ID.  
* The process: For each polygon (focal unit) the algorithm computes the distance to every other polygon and flags those whose distance falls inside the specified band.
* **The output**: a graph where each node has edges to all nodes ('neighbors') whose representative points lie within the radius. Edges are represented by a continuous adjacency matrix, the default values represent the inverse distance between the nodes in the edges.

Here it is:
"""

band750k_C=Graph.build_distance_band(sub_us.representative_point(), threshold=750000,binary=False)

band750k_C_Matrix=toWideMatrix(band750k_C)
band750k_C_Matrix

"""The plot:"""

band750k_C.explore(**basic_arguments)

"""Above, you do not see the continuous information present in the edges, for that, you may plot one of the states using **focal=**:"""

# pay attention to one state:
focal_args=dict(gdf=sub_us,focal='Arizona',edge_kws=dict(column="weight",style_kwds=dict(weight=6)),zoom_start=6)
band750k_C.explore(**focal_args)

"""#### I.2.2 Kernel K-Nearest Neighbors (KNN)

* The key idea: Each polygon keeps only other  K closest polygons, but instead of a blunt 0 / 1 the tie is a gentle “friendliness” score that shrinks with distance.  
* The input: A GeoDataFrame of polygons + their representative points.  
* The process:  
  – Find the K nearest points.  
  – Turn distance into a Gaussian bell value (big when close, small when far).  

* The output: A weighted graph where every node has exactly K neighbours carrying continuous “soft” weights; no islands, no huge clumps, just K tidy friendship levels per row.

Let's use K = 3 again:
"""

kernel3 = Graph.build_kernel(sub_us.representative_point(), k=3)

kernel3_Matrix=toWideMatrix(kernel3)
kernel3_Matrix

"""Notice we have bigger values that the continuous band-based result. Let's see the basic plot:"""

kernel3.explore(**basic_arguments)

"""Plot one of the states using **focal=**:"""

kernel3.explore(**focal_args)

"""#### I.2.3 Perimeter-based Proximity


* **The key idea**: A focal polygon treats another polygon as a neighbour only if the two share a common border.  
* **The input**: A GeoDataFrame of polygons; no extra points needed.  
* **The process**:  
  – Compute the exact length of every shared boundary segment.  
  – Set w_ij = shared_perimeter_ij (zero if no border).  
  
* **The output**: A weighted graph encoded in a sparse weights matrix; each non-zero entry is the **metres (or map-units) of shared border**, giving large, jagged polygons more influence over their neighbours than small, compact ones.
"""

perimeter = Graph.build_contiguity(sub_us, by_perimeter=True) #rook by default

perimeter_Matrix=toWideMatrix(perimeter)
perimeter_Matrix

"""The basic plot:"""

perimeter.explore(**basic_arguments)

"""Plot one of the states using **focal=**:"""

perimeter.explore(**focal_args)

"""In summary:

| Technique | Pros | Cons | Typical use-case example |
|-----------|------|------|--------------------------|
| **Rook / Queen contiguity** | Simple, law- or admin-based, no distance parameter | Islands get 0 neighbours; ignores “near but not touching” units | State-to-state policy diffusion, local tax spill-overs |
| **K-NN (binary)** | Guarantees every unit has same #neighbours; no islands | Can link far-away units in sparse areas; ignores true borders | Comparative politics with same-size legislatures, small-N samples |
| **Distance band (binary)** | Hard cap on geographic reach; easy to interpret radius | Sparse → islands; dense → huge cliques; radius must be tuned | Housing-price spill-overs within 30 km commuting range |
| **Continuous distance-band** | Smooth weights, still respects max range | Same radius-tuning and island issues as binary band | Environmental exposure declining with distance, gravity models |
| **Kernel K-NN** | Fixed neighbour count, adaptive bandwidth, no islands | Far neighbours possible in deserts/oceans; parameter k to pick | As input for regression or ML models |
| **Perimeter-weighted contiguity** | Uses real boundary, good for irregular shapes | Needs clean topology; computation heavier | Ecological edge effects, river-basin pollution, crop pest spread |

## II. Neighborhoods as weights

Our matrices tell us which are neighbors, and some give us additional information related to the 'farness' of the identified neighbor. Let me compute the marginal values by row (sum):
"""

allMx=[rook_Matrix.sum(axis=1),
       queen_Matrix.sum(axis=1),
       knn3_Matrix.sum(axis=1),
       band750k_Bi_Matrix.sum(axis=1),
       band750k_C_Matrix.sum(axis=1),
       kernel3_Matrix.sum(axis=1),
       perimeter_Matrix.sum(axis=1)]
pd.concat(allMx,axis=1)

"""We know that no-neighbors have value zero in the matrix. Then, non-zero (binary or non-binary) values carries some weight .
However, they are currently not normalized (they do not add to 1 by row), which may complicate further computations.

For example, this binary matrix is non-normalized:
"""

queen_Matrix

"""But this binary matrix is normalized (by **r**ows):"""

queen.transform("r").adjacency.unstack().fillna(0)

"""Another example, this binary matrix is non-normalized"""

perimeter_Matrix

"""Here it is normalized:"""

perimeter.transform("r").adjacency.unstack().fillna(0)

"""These new row-standardized matrices will serve a greater purpose: the computing of spatial lags.

## III. How are my neighbors doing...? - intro to spatial lag

The actual question should be related to a social variable, for example, poverty, mortality, education, etc.

For example, this is "how each distrito is doing" related to HS education (share of population that completed high school):
"""

peru_distritos.Educ_sec_comp2019_pct.describe()

"""See the choropleth:"""

peru_distritos.plot(
    "Educ_sec_comp2019_pct",
    scheme="quantiles",
    cmap="Reds_r",
    legend=True,figsize=(12, 10))

"""The title was asking about the situation of neighbors (the **neighbors** of each **focal** in my data). If the focals can have a variable that summarizes the average of their neighbors, the have computed the **spatial lag** of that variable.

Then, if this graph has the adjacency of the districts:
"""

peru_distritos_queen=Graph.build_contiguity(peru_distritos,rook=False)

"""And here you normalize the adjacency:"""

peru_distritos_queen=peru_distritos_queen.transform("r")

"""This gives you the spatial lag of the variable "Educ_sec_comp2019_pct":"""

ylag = peru_distritos_queen.lag(peru_distritos["Educ_sec_comp2019_pct"])

"""Let me add it to the GDF:"""

peru_distritos=peru_distritos.assign(Educ_sec_comp2019_pct_lagged=ylag)

"""Let's plot HS share against its lag:"""

peru_distritos.plot.scatter("Educ_sec_comp2019_pct","Educ_sec_comp2019_pct_lagged")

"""## IV. Spatial correlation

### IV. 1 Global

A correlation plot as the previous one should let us know if a variable is correlated with values of the neighbors (the lag), and if that were the case,  proximity is interfering statistical analysis, as the variable values are not independent.

The most well known measure to confirm that is the Moran's I index of global spatial correlation. Let's see the value we get:
"""

import esda # from pysal

MoranGlobal_HS = esda.Moran(peru_distritos['Educ_sec_comp2019_pct'], peru_distritos_queen)

"""Once computed, you can retrieve its value and significance:"""

MoranGlobal_HS.I,MoranGlobal_HS.p_sim

"""Moran’s I is interpreted like a Pearson r, but benchmarks are lower:

- |I| > 0.5 → strong, 0.2–0.5 → moderate, < 0.2 → weak.
- Sign indicates positive vs. negative spatial clustering.

Significance is assessed with a pseudo p-value from conditional randomisations of the data, because the theoretical null distribution is unknown for irregular spatial weights.

### IV. 2 Local Spatial Correlation

We can compute a Local Index of Spatial Association (LISA -local Moran) for each map polygon. That will help us find spatial clusters (spots) and spatial outliers:

- High-High (HH): values above average surrounded by values above average.**hotSpot**
- Low-Low (LL): values below average surrounded by values below average. **coldSpot**
- High-Low (HL): values above average surrounded by values below average.**hotOutlier**
- Low-High (LH): values below average surrounded by values above average. **coldOutlier**

It is also possible that no significant correlation is detected. Let's see those values:

a. Compute the LISAs:
"""

lisa = esda.Moran_Local(peru_distritos['Educ_sec_comp2019_pct'], peru_distritos_queen)

"""The previous warning may be due to the presence of islands, produced by queen algorithm:"""

peru_distritos_queen.isolates

"""This islands may create trouble. Should you keep using a _contiguity_ approach, you may consider fltering those out and recompute ``graph`` and ``lisa``:"""

islandCodes = peru_distritos_queen.isolates
peru_clean=peru_distritos.drop(index=islandCodes).copy()
peru_queen_clean=Graph.build_contiguity(peru_clean,rook=False).transform("r")
#
lisa = esda.Moran_Local(peru_clean['Educ_sec_comp2019_pct'], peru_queen_clean)

"""b. Plot the results (**fast way**)"""

lisa.explore(peru_clean,crit_value=0.05,  tiles="CartoDB Positron")

"""#### IV. 2. 1 Analysis Local Spatial Correlation quadrants

You can not get the quadrant labels from the previous plot directly into the original GDF, thus complicating further analysis and exporting of those results.

First let's recover the labels into a new column:
"""

# get the quadrants
peru_clean['HS_lisa'] = lisa.get_cluster_labels(crit_value=0.05)

# see the count
peru_clean['HS_lisa'].value_counts()

"""Now, we can prepare this a comparisson:"""

TheStats=["mean", "min", "max","var"]


# stats by the lisa cluster
grouped_stats = peru_clean.groupby('HS_lisa')['Educ_sec_comp2019_pct'].agg(TheStats)

# stats for the entire, ungrouped column
global_stats = peru_clean['Educ_sec_comp2019_pct'].agg(TheStats)

# Convert 'global_stats' (Series) to a DataFrame with an appropriate index name
global_stats_df = pd.DataFrame(global_stats).T
global_stats_df.index = ['Global/Total'] # simple but key

# Combine both
pd.concat([grouped_stats, global_stats_df])

"""From the results above, you may have several concerns and keep asking more questions:

- High-High clusters are concentrated areas of high percent of graduation from HighSchool. Is that expected in those areas? What has caused that? Has this been the same for a long time?

- Low-Low clusters are concentrated areas of low percent of graduetion from HighSchool. What would it take to make a change in these areas? No doubt some kind of intervention is needed.

- High-Low clusters detect districts that outperform their neighbors. Can we leverage on those to improve the area? Are they in danger of worsening?

- Low-High clusters detect districts that are much worse than their neighbors, who are actually doing pretty well. Can we improve this place considering the surroundings need less intervention or not at all?

#### IV. 2. 2 Customizing Local Spatial Correlation quadrants

At this stage, we can rename the previous column to customize cluster labels and colors:
"""

##knowing
peru_clean['HS_lisa'].unique()

"""Keep in mind that the outliers may deserve more attention, so they may be at the top or bottom of the levels. You can add a number to achieve this purpose:"""

oldLabels=peru_clean['HS_lisa'].unique()

# 3 will be at the middle
newLabels = [ '2 hotSpot','3 no_pattern', '5 coldOutlier','1 hotOutlier', '4 coldSpot', ]

labels = dict(zip(oldLabels, newLabels))

labels

"""Just using this dictionary to rename the column:"""

peru_clean.replace({'HS_lisa':labels},inplace=True)

## see the count
peru_clean['HS_lisa'].value_counts().sort_index()

"""Finally, used that order to assign color-blind safe palette:"""

##custom colors- respect the previous order

import matplotlib.pyplot as plt
myColMap = plt.get_cmap('PuOr', 5)


##plot the map

peru_clean.plot(column='HS_lisa',
                categorical=True,
                cmap=myColMap,
                linewidth=0.1,
                edgecolor='k',
                legend=True,
                legend_kwds={'bbox_to_anchor': (0.3, 0.3)},
                figsize=(12,12))

